# Generated by Django 6.1 on 2026-09-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cryptocurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
