# Generated by Django 6.1 on 2026-09-01 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0005_delete_cryptocurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, default=0.0, max_digits=18)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.cryptocurrency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_assets', to='users.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'crypto')},
            },
        ),
    ]
