# Generated by Django 6.1 on 2026-09-01 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('users', '0006_walletasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price_at_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.cryptocurrency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='users.wallet')),
            ],
        ),
    ]
