[project]
name = "cryptoflow"
version = "0.1.0"
description = "Plataforma gamificada de investimentos em criptomoedas"
readme = "README.md"
authors = [
    { email = "contato.thalyssondel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.3",
    "django>=6.1",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "requests>=2.34.2",
]

[tool.uv]
package = false
